# Generated by Django 5.2.17 on 2026-09-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Block', 'Block'), ('Unblock', 'Unblock')], default='Unblock', max_length=10),
        ),
    ]
